# Generated by Django 5.2.4 on 2025-11-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_delete_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
