# Generated by Django 5.2.4 on 2025-11-25 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/')),
                ('focus_body_part', models.CharField(blank=True, choices=[('arms', 'Arms'), ('legs', 'Legs'), ('chest', 'Chest'), ('back', 'Back'), ('abs', 'Abs'), ('full', 'Full Body')], max_length=100, null=True)),
                ('goal', models.CharField(blank=True, choices=[('strength', 'Build Strength'), ('weight_loss', 'Lose Weight'), ('endurance', 'Improve Endurance'), ('flexibility', 'Increase Flexibility')], max_length=100, null=True)),
                ('exercise_type', models.CharField(blank=True, choices=[('cardio', 'Cardio'), ('weights', 'Weights'), ('yoga', 'Yoga'), ('hiit', 'HIIT'), ('calisthenics', 'Calisthenics')], max_length=100, null=True)),
                ('is_member', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
