# Generated by Django 5.2.4 on 2025-12-07 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('detailed_instructions', models.TextField(blank=True, help_text='Step-by-step guide on how to perform the exercise safely.')),
                ('image', models.ImageField(blank=True, help_text='Upload an illustrative image of the exercise.', null=True, upload_to='exercises/images/')),
                ('video_url', models.URLField(blank=True, help_text='Link to a video demo (YouTube or mp4 URL).', null=True)),
                ('body_part', models.CharField(choices=[('arms', 'Arms'), ('legs', 'Legs'), ('chest', 'Chest'), ('back', 'Back'), ('abs', 'Abs'), ('full', 'Full Body')], max_length=20)),
                ('goal', models.CharField(choices=[('strength', 'Build Strength'), ('weight_loss', 'Lose Weight'), ('endurance', 'Improve Endurance'), ('flexibility', 'Increase Flexibility')], max_length=20)),
                ('exercise_type', models.CharField(choices=[('cardio', 'Cardio'), ('weights', 'Weights'), ('yoga', 'Yoga'), ('hiit', 'HIIT'), ('calisthenics', 'Calisthenics')], max_length=20)),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('equipment', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, help_text='Shown on the program card in the UI.', max_length=255)),
                ('long_description', models.TextField(blank=True, help_text='Detailed explanation of what this program includes.')),
                ('image', models.ImageField(blank=True, help_text='Thumbnail image used in the program card.', null=True, upload_to='programs/images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(default=1, help_text='Day of the program (e.g., 1 for Day 1).')),
                ('order', models.PositiveIntegerField(default=1, help_text="Position of this exercise inside the day's sequence.")),
                ('sets', models.PositiveIntegerField(blank=True, help_text='Number of sets (optional).', null=True)),
                ('reps', models.CharField(blank=True, help_text="Reps or duration (e.g., '12', '30 sec').", max_length=50)),
                ('exercise', models.ForeignKey(help_text='The exercise being added to this program.', on_delete=django.db.models.deletion.CASCADE, to='workouts.exercise')),
                ('program', models.ForeignKey(help_text='The program this exercise belongs to.', on_delete=django.db.models.deletion.CASCADE, to='workouts.program')),
            ],
            options={
                'ordering': ['day_number', 'order'],
            },
        ),
    ]
