# Generated by Django 5.2.4 on 2025-12-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exerciseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_premium',
            field=models.BooleanField(default=True, help_text='If checked, this program requires premium membership.'),
        ),
    ]
