# Generated by Django 5.2.4 on 2025-12-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_program_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='is_premium',
        ),
    ]
