# Generated by Django 5.2.4 on 2025-12-26 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_program_is_premium'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseImage',
        ),
    ]
