# Generated by Django 5.2.4 on 2025-12-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
