# Generated by Django 5.2.4 on 2026-01-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='quantity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='food',
            name='serving_qty',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='food',
            name='serving_unit',
            field=models.CharField(default='serving', max_length=50),
        ),
    ]
